[DCE-153] Walking Skeleton
ampats/Practice-basic-webapi-application pull request #1
Opened 2024-01-18 09:25 UTC by ampats

Create scaffolding for dotnet application

Checklist:
- [ ] main branch is protected
- [x] includes PR template
- [x] github action that writes hello-world using ubuntu runner
- [x] basic dotnet web app that writes "Hello World" (do not do any other development)
- [x] contains README on how to run the application locally as an ubuntu user
- [x] should contain gitignore

2024-01-18 10:57 UTC, Kterlecki commented
Great Work! Could you just look through some of the requirements for this Jira story, I believe a few are missing
- Readme
- Completed github action - remove the run
- etc. 
- you can leave it for this project, but try to build directories in src/nameOfProject/*.csproj.

2024-01-19 13:15 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
> +      - feature/DCE-153-walking-skeleton
```suggestion
```

2024-01-19 13:15 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
> +
```suggestion
```

2024-01-19 16:07 UTC, sethpthomas91 requested changes
Great first pass. Please take a look at the Jira story and make sure everything is covered.

2024-01-19 16:07 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
> +      run: echo ${{ github.event.client_payload.text }}
```suggestion
    - name: Build
      run: echo "Hello, World"
```

2024-01-22 13:11 UTC, sethpthomas91 requested changes
Very small changes, but after that this will be approved!

2024-01-22 13:11 UTC, sethpthomas91 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Color contrast tested?
Great job using resources, but please take a look at the code before copying and pasting! Turn this into your own.

2024-01-22 13:11 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
> +    #[self-hosted, linux, x64, dm-dq-dynamic-runner, dotnet, ubuntu-latest]
```suggestion
```

2024-01-22 13:11 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
> +# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
```suggestion
```
Don't forget to clean up boiler plate code. Look at everything before you request a review and make sure you clean up unnecessary comments.

2024-01-22 14:03 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
> +    name: Webhook Test
Is this still a webhook test?

2024-01-22 14:04 UTC, sethpthomas91 approved these changes
Take a look at my one comment and please address that before squashing a merging this one. You are free to squash a merge though once that is done!

2024-01-22 14:37 UTC, merged