[DCE-154] Walking Skeleton - Artifacts
ampats/Practice-basic-webapi-application pull request #3
Opened 2024-01-29 15:29 UTC by ampats

## Jira Story link: https://jira.pfizer.com/browse/DCE-154

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Optimization
- [ ] Test
- [ ] Build
- [ ] Documentation Update

## Description
Create an artifact of the web application to download and use on user's local  Windows machine to run the app. 
This artifact should contain 
- [ ] a binary and 
- [ ] a README with instructions to run this application on user's local Windows machine

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Color contrast tested?

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?

2024-01-29 15:39 UTC, ampats commented
Should I also fix sln file as shown in last week's call?

2024-01-29 16:24 UTC, sethpthomas91 requested changes

2024-01-29 16:24 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
>        run: echo "Hello, World"
```suggestion
```
Not needed

2024-01-29 16:24 UTC, sethpthomas91 commented on .github/workflows/practice-basic-webapi-application.yml
Getting the following warning on your githubaction:
<img width="1043" alt="Screenshot 2024-01-29 at 11 23 04 AM" src="https://github.com/ampats/Practice-basic-webapi-application/assets/86486985/5787ee79-6ad7-423c-b94b-cd5697181caf">
Can we see if we can get rid of that?

2024-01-29 16:24 UTC, sethpthomas91 commented on README-artifact.md
Fantastic instructions

2024-01-29 16:27 UTC, sethpthomas91 commented
Please also fix the name of the PR to be [DCE-154] Publish Artifact

2024-01-29 16:27 UTC, sethpthomas91 commented
> Should I also fix sln file as shown in last week's call?

You can do this in another PR. Keep your PRs as single focus as possible.

2024-01-29 16:50 UTC, ampats commented on README-artifact.md
Thank you! :)

2024-01-29 16:59 UTC, sethpthomas91 commented on README-artifact.md
For this file, I would look into some different approaches than keeping two READMEs on the same level. Should there be a release docs directory with this inside? Should these instructions be placed with the overall README and that is just included with the artifact?

2024-01-30 13:11 UTC, sethpthomas91 approved these changes
Great job!

2024-01-30 15:09 UTC, merged